### ISSUE TITLE
补全文档

### ISSUE THREAD

**Issue by idootop** [foca-js/foca#1]
啥时候出文档和example啊？

**Comment by fwh1990** [comment]
框架趋近成熟，公司内部项目已经用了一段时间，文档地址：https://foca-js.github.io/foca/ 

axios增强型请求库也有了，这几天补上文档。也可以看看demo集合：https://github.com/foca-js/foca-demos
请求库是可选的，不一定要用，但用了一定会爽。

欢迎提供点子，以及新的建议意见。（很需要）

**Comment by idootop** [comment]
> 框架趋近成熟，公司内部项目已经用了一段时间，文档地址：https://foca-js.github.io/foca/
> 
> axios增强型请求库也有了，这几天补上文档。也可以看看demo集合：https://github.com/foca-js/foca-demos 请求库是可选的，不一定要用，但用了一定会爽。
> 
> 欢迎提供点子，以及新的建议意见。（很需要）

thx.  做的很好，祝foca越来越好。
