### ISSUE TITLE
一定要在 effects 中使用 this.setState 或者 先定义 actions 方法调用才能更新状态吗

### ISSUE THREAD

**Issue by Handpear** [foca-js/foca#21]
我不想在我的代码的任何地方出现 this
如果只能先定义 actions，那么每个接口的增删改查都要先定义，有点太费事了

或者可以在 UI 层暴露一个 useSetState ?

**Comment by geekact** [comment]
this没有传闻的那么可怕，它不需要像react class中的事件回调一样需要bind(this)。如果你实在不想用this，用变量也行。`const testModel = defineModel()`，使用testModel代替this，不过这样就失去了`私有方法, 克隆模型, 局部模型` 等诸多高级特性。

定义actions的作用一方面是增强**复用性**；另一方面是**约束**。如果任何地方均能修改状态，那么项目大了之后就容易失控，直接修改状态的逻辑散落在各个组件，我想这也是为什么[mobx](https://github.com/mobxjs/mobx)推荐配置`enforceActions`。

相对于原生redux，我们可以把`太费事`改成`超级省事`。

使用`useSetState`不如直接用`React.useState`？需要响应式再加个immer即可。

另外，[mobx](https://github.com/mobxjs/mobx)应该比较符合你现阶段的需求，值得一试 :)

**Comment by Handpear** [comment]
无 this 是因为代码风格的问题。还有一点不太明白，使用 this.setState 为什么一定要传完整的 state 呢，api 风格更像原生的 this.setState({ key: value}) 是不是更方便一点

**Comment by geekact** [comment]
也可以这么用
```typescript
this.setState((state) => {
  state.key = value;
});
```
至于是否需要能传递残缺的state，还没有考虑过这个问题，可能是实现的时候为了省事，我这边调研一下是否能实现。

**Comment by Handpear** [comment]
@geekact 
感谢，加油

**Comment by geekact** [comment]
经过测试和研究，是可以这么做的。已经提交commit https://github.com/foca-js/foca/commit/7dcc2a32c0557876de71c9ccc367b7779e781d5c ，将在版本 1.1.0 中体现

**Comment by smartPiz** [comment]
赞同，确实是可以简化
