### ISSUE TITLE
关于持久化的版本号

### ISSUE THREAD

**Issue by Handpear** [foca-js/foca#22]
1、如何升级版本号，比如我使用 [localforage](https://www.npmjs.com/package/localforage) 作为引擎，似乎文档中没有更详细的说明。
2、如果升级了版本号是清空所有开启持久化的模型还是只清空某个模型？

**Comment by geekact** [comment]
* 在store.init()中升级版本号是清空所有模型
* 在model.persist中升级版本号则是清空当前模型

**Comment by Handpear** [comment]
store中的我懂了，就相当于执行一次store的初始化，我想问在业务组件中怎么修改model.persist，我看见是挂载到_$opts中的

**Comment by geekact** [comment]
```diff
const model = defineModel({
  initialState,
+ persist: {
+   version: 1,
+ },
});
```
也是一段配置，运行时不能修改

**Comment by Handpear** [comment]
运行时不能修改吗，这原来是一种手动操作呀QAQ

**Comment by geekact** [comment]
是的，相当于是覆盖全局的持久化配置。另外我更新了version的文档说明以及使用建议，希望能给你提供更多的帮助 https://foca.js.org/#/persist?id=version

**Comment by Handpear** [comment]
@geekact 
感谢
