### ISSUE TITLE
actions,异步actions, reducer, methods, computed, watch 名称叫法

### ISSUE THREAD

**Issue by SoonIter** [foca-js/foca#29]
effects这个词，给我的感觉更多是副作用，类似watch监听导致的watchEffect，或者是useEffect产生的副作用。如果watch特性上线，应该给effect换名的。
我的提议是把异步action放到actions，不知道判断一下返回值为Promise可不可以实现。

**Comment by geekact** [comment]
actions在部分状态库中叫 reducers，叫法上后者比较贴切；
effects确实提供了副作用的功能，比如 `setState`，比如 `loading`；
而watch特性应该会直接开一个watch属性；
至于普通的返回，其实更应该叫做`methods`，只不过effects也能返回数据，所以就合并在一起了。

这个问题我也想了挺久，也参考了其他库的规范，但是没有统一的定论。

命名这块，可谓仁者见仁。后期可能会修改的方案：
- `actions` -> `reducers`
- `effects` -> `methods`
