### ISSUE TITLE
React native storage

### ISSUE THREAD

**Issue by lhr000lhr** [foca-js/foca#3]
Hi there,

Just wondering how to persist data in React native.

**Comment by fwh1990** [comment]
Sorry, I'm late. Just import [async-storage](https://www.npmjs.com/package/@react-native-async-storage/async-storage)
```typescript
import AsyncStorage from @react-native-async-storage/async-storage;
store.init({
  persist: [
    {
        engines: AsyncStorage,
        ....,
    }
  ]
});
```
