### ISSUE TITLE
持久化没有把initvalue放进去

### ISSUE THREAD

**Issue by day-xue** [foca-js/foca#37]
持久化插件，只有在状态变更的时候才会触发，期望把initvalue在oninit 的时候就放在缓存里，如果不放在缓存里可能有一些预期的错误

**Comment by day-xue** [comment]
如果开启持久化 只用了一个model 在devtool 只看到这个model 其他model没有

**Comment by geekact** [comment]
> 如果不放在缓存里可能有一些预期的错误

我目前没有遇到报错，能说说你的场景吗？



> 如果开启持久化 只用了一个model 在devtool 只看到这个model 其他model没有

是的，因为模型总是在组件中使用，所以如果你的路由组件有使用`lazy import`之类的方案，它就被webpack或者vite打包工具`分割`到不同的页面。所以路由组件不载入浏览器，模型就不会被发现。
而持久化的模型因为一开始就在入口被import了，所以自然就被注册了。

**Comment by geekact** [comment]
v3版本开始，initialState会立即存入持久化
