### ISSUE TITLE
有办法删除Model吗?

### ISSUE THREAD

**Issue by d380025303** [foca-js/foca#42]
如题，很多情况下页面切换后，之前的Model已经不用了（或者说重新进入我希望创建新的Model）
这种场景下Model能卸载掉吗?

**Comment by geekact** [comment]
v3之前出过一个 `useDefined`的钩子，[文档在这](https://github.com/foca-js/foca/blob/v2/docs/advanced.md#%E5%B1%80%E9%83%A8%E6%A8%A1%E5%9E%8B)。不知道是不是你想要的。v3删掉是因为这个名字太难听了，但是我今天想起一个更贴切的名字`useIsolate`

**Comment by d380025303** [comment]
嗯 我之前确实看到有useDefine, 3.0.0之后看您删掉了, 还以为有更好的方案
看了您的源代码, modelStore有个removeReducer方法, 调用之后已经可以手动卸载掉不用的reducer了, 我觉得还挺方便的, 由于对ts不太熟, 看您后续有没有计划能放出手动卸载的方法, 还是挺实用的

**Comment by geekact** [comment]
手动卸载不是一个好办法，我打算在 v3.2 版本把这个功能加回来并重新取名`useIsolate`。另外如果你对这个钩子有其它的建议也可以畅所欲言

**Comment by geekact** [comment]
已发布 v3.2.0 。有任何问题请随时告诉我
