### ISSUE TITLE
给点建议

### ISSUE THREAD

**Issue by arcsin1** [foca-js/foca#5]
可以把reselect 接入进去，会带来更好的优化

**Comment by fwh1990** [comment]
尝试过，不过reselect的依赖项属于业务需求，集成恐怕不太现实。有什么思路吗？

**Comment by lhr000lhr** [comment]
I am also looking forward to having it.

**Comment by arcsin1** [comment]
> 尝试过，不过reselect的依赖项属于业务需求，集成恐怕不太现实。有什么思路吗？

en，看了下实现，其实是不需要了，因为已经有immer了。加入了或许会有一些负担。你这个model实现很好用，已经让我团队在用了，感谢!

**Comment by geekact** [comment]
@lhr000lhr  0.11.0 模型增加了computed属性，文档：https://foca.js.org/#/model?id=computed ，也许会是你们想要的
